version: "3.1"
services:
  database:
    image: "postgres:14"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anaisdocker
      POSTGRES_DB: postgres
      PGTZ: Europe/Paris
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
  nodejs:
    build: .
    environment:
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
      - SPOTIFY_REDIRECT_URI
      - SPOTIFY_ACCESS_TOKEN
      - SPOTIFY_REFRESH_TOKEN
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET
      - PGHOST
      - PGUSER
      - PGPASSWORD
      - TZ
      - PGTZ
      - APP_ENV
      - STATS_LANG
    depends_on:
      - database
    restart: unless-stopped
volumes:
  database-data:
