version: "3.1"
services:
  database:
    image: "postgres:14"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anaisdocker
      POSTGRES_DB: postgres
      PGTZ: Europe/Paris
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
  nodejs:
    build: .
    environment:
      - spotify_clientId
      - spotify_clientSecret
      - spotify_redirectUri
      - spotify_accessToken
      - spotify_refreshToken
      - twitter_consumer_key
      - twitter_consumer_secret
      - twitter_access_token
      - twitter_access_token_secret
      - PGHOST
      - PGUSER
      - PGPASSWORD
      - TZ
      - PGTZ
    depends_on:
      - database
    restart: unless-stopped
volumes:
  database-data:
